# Generated by Django 5.1 on 2024-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showing',
            field=models.BooleanField(default=True),
        ),
    ]
