# Generated by Django 5.1 on 2024-10-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_showing'),
        ('register', '0003_profile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='posts.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='register.profile')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('userid', 'postid')},
            },
        ),
    ]
