# Generated by Django 5.1 on 2024-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('v1', 'Other'), ('v2', 'MCA'), ('v3', 'MBA'), ('v4', 'B-Tech')], max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, default='This is your bio', null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
