# Generated by Django 5.1 on 2024-09-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_no',
            field=models.CharField(default='NONE', max_length=150),
        ),
    ]
