# Generated by Django 5.1 on 2024-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='added',
            field=models.DateTimeField(default='2024-01-01'),
        ),
    ]
