# Generated by Django 5.1 on 2024-10-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_magazine_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
